// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Dv8CEw5C8tJQecXMeWd2aIMl_kqdwmY',
    appId: '1:460369923259:web:a7d71d1f47a9b291a92d9e',
    messagingSenderId: '460369923259',
    projectId: 'py55-7ec9c',
    authDomain: 'py55-7ec9c.firebaseapp.com',
    storageBucket: 'py55-7ec9c.firebasestorage.app',
    measurementId: 'G-0YXJ00300Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8zDCE_244pIgdymA3BPLP8QXCv3RK0Q',
    appId: '1:460369923259:android:0553f588eafdc2bda92d9e',
    messagingSenderId: '460369923259',
    projectId: 'py55-7ec9c',
    storageBucket: 'py55-7ec9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-HAFVFK5zw--L4hLJHwc4MSb-rBvEOdc',
    appId: '1:460369923259:ios:9601f6795e64610aa92d9e',
    messagingSenderId: '460369923259',
    projectId: 'py55-7ec9c',
    storageBucket: 'py55-7ec9c.firebasestorage.app',
    iosBundleId: 'com.py55.py55',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-HAFVFK5zw--L4hLJHwc4MSb-rBvEOdc',
    appId: '1:460369923259:ios:9601f6795e64610aa92d9e',
    messagingSenderId: '460369923259',
    projectId: 'py55-7ec9c',
    storageBucket: 'py55-7ec9c.firebasestorage.app',
    iosBundleId: 'com.py55.py55',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Dv8CEw5C8tJQecXMeWd2aIMl_kqdwmY',
    appId: '1:460369923259:web:e1528ecbd8469b0ba92d9e',
    messagingSenderId: '460369923259',
    projectId: 'py55-7ec9c',
    authDomain: 'py55-7ec9c.firebaseapp.com',
    storageBucket: 'py55-7ec9c.firebasestorage.app',
    measurementId: 'G-9HNLCCF3PK',
  );
}
